// Generated by gen_checker_inst.py


bit[31:0] op1_SHA512SIG1L_t0;
assign op1_SHA512SIG1L_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SHA512SIG1L_t0;
assign op2_SHA512SIG1L_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_AES32DSI_t0;
assign op1_AES32DSI_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES32DSI_t0;
assign op2_AES32DSI_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SM4ED_t0;
assign op1_SM4ED_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SM4ED_t0;
assign op2_SM4ED_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA512SUM1_t0;
assign op1_SHA512SUM1_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES32ESI_t0;
assign op1_AES32ESI_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES32ESI_t0;
assign op2_AES32ESI_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA512SUM1R_t0;
assign op1_SHA512SUM1R_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SHA512SUM1R_t0;
assign op2_SHA512SUM1R_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA512SIG0L_t0;
assign op1_SHA512SIG0L_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SHA512SIG0L_t0;
assign op2_SHA512SIG0L_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SM3P1_t0;
assign op1_SM3P1_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_SM3P0_t0;
assign op1_SM3P0_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES64ES_t0;
assign op1_AES64ES_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES64ES_t0;
assign op2_AES64ES_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA256SIG1_t0;
assign op1_SHA256SIG1_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES64IM_t0;
assign op1_AES64IM_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_SHA512SUM0R_t0;
assign op1_SHA512SUM0R_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SHA512SUM0R_t0;
assign op2_SHA512SUM0R_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_AES32DSMI_t0;
assign op1_AES32DSMI_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES32DSMI_t0;
assign op2_AES32DSMI_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA512SUM0_t0;
assign op1_SHA512SUM0_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_SHA512SIG0_t0;
assign op1_SHA512SIG0_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES64ESM_t0;
assign op1_AES64ESM_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES64ESM_t0;
assign op2_AES64ESM_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_AES64KS1I_t0;
assign op1_AES64KS1I_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES64KS2_t0;
assign op1_AES64KS2_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES64KS2_t0;
assign op2_AES64KS2_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA256SIG0_t0;
assign op1_SHA256SIG0_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES64DSM_t0;
assign op1_AES64DSM_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES64DSM_t0;
assign op2_AES64DSM_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_AES64DS_t0;
assign op1_AES64DS_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES64DS_t0;
assign op2_AES64DS_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA512SIG0H_t0;
assign op1_SHA512SIG0H_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SHA512SIG0H_t0;
assign op2_SHA512SIG0H_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA256SUM0_t0;
assign op1_SHA256SUM0_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_SHA512SIG1H_t0;
assign op1_SHA512SIG1H_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SHA512SIG1H_t0;
assign op2_SHA512SIG1H_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA512SIG1_t0;
assign op1_SHA512SIG1_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_SM4KS_t0;
assign op1_SM4KS_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_SM4KS_t0;
assign op2_SM4KS_t0 = i_pipeline__i_gprs__rs2_data_t0;

bit[31:0] op1_SHA256SUM1_t0;
assign op1_SHA256SUM1_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op1_AES32ESMI_t0;
assign op1_AES32ESMI_t0 = i_pipeline__i_gprs__rs1_data_t0;

bit[31:0] op2_AES32ESMI_t0;
assign op2_AES32ESMI_t0 = i_pipeline__i_gprs__rs2_data_t0;

