# Generated by /data/kceesay/workspace/cellift-formal/py_scripts/fpv_core_setup/taint_states.py
proc no_taint_in_symb_init {taskName} {

assume -task $taskName -bound 1 {core_clock_gate_i.en_latch_t0 == 0 }
assume -task $taskName -bound 1 {{\g_clock_en_secure.u_prim_core_busy_flop .\gen_generic.u_impl_generic .q_o_t0} == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i._3299_ == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.priv_mode_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.branch_jump_set_done_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.branch_set_raw_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.id_fsm_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.imd_val_q_ex_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.dummy_instr_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.illegal_c_insn_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_fetch_err_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_fetch_err_plus2_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_is_compressed_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_new_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_rdata_alu_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_rdata_c_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.instr_valid_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.if_stage_i.pc_id_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.addr_last_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.data_sign_ext_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.data_type_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.data_we_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.handle_misaligned_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.ls_fsm_cs_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.lsu_err_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.pmp_err_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.rdata_offset_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.load_store_unit_i.rdata_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.mcycle_counter_i.counter_val_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.minstret_counter_i.counter_val_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_cpuctrlsts_part_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_dcsr_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_depc_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_dscratch0_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_dscratch1_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mcause_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mepc_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mie_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mscratch_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mstack_cause_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mstack_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mstack_epc_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mstatus_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mtval_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.cs_registers_i.u_mtvec_csr.rd_data_o_t0 == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.ex_block_i.\gen_multdiv_slow.multdiv_i .div_by_zero_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.ex_block_i.\gen_multdiv_slow.multdiv_i .md_state_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.ex_block_i.\gen_multdiv_slow.multdiv_i .multdiv_count_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.ex_block_i.\gen_multdiv_slow.multdiv_i .op_a_shift_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.ex_block_i.\gen_multdiv_slow.multdiv_i .op_b_shift_q_t0} == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.ctrl_fsm_cs_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.debug_cause_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.debug_mode_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.do_single_step_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.enter_debug_mode_prio_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.exc_req_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.illegal_insn_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.load_err_q_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.nmi_mode_o_t0 == 0 }
assume -task $taskName -bound 1 {u_ibex_core.id_stage_i.controller_i.store_err_q_t0 == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_dummy_instr.dummy_instr_i .dummy_cnt_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_dummy_instr.dummy_instr_i .dummy_instr_seed_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .branch_discard_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .discard_req_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .fetch_addr_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .rdata_outstanding_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .stored_addr_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .valid_req_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_dummy_instr.dummy_instr_i .lfsr_i.lfsr_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .fifo_i.err_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .fifo_i.instr_addr_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .fifo_i.rdata_q_t0} == 0 }
assume -task $taskName -bound 1 {{u_ibex_core.if_stage_i.\gen_prefetch_buffer.prefetch_buffer_i .fifo_i.valid_q_t0} == 0 }
}