# Generated by /data/kceesay/workspace/mucfi/automation/fpv_core_setup/taint_states.py
proc no_taint_in_symb_init {taskName} {

assume -task $taskName -bound 1 {_00077_ == 0 }
assume -task $taskName -bound 1 {_00079_ == 0 }
assume -task $taskName -bound 1 {_05746_ == 0 }
assume -task $taskName -bound 1 {_06583_ == 0 }
assume -task $taskName -bound 1 {_06585_ == 0 }
assume -task $taskName -bound 1 {_06586_ == 0 }
assume -task $taskName -bound 1 {_06589_ == 0 }
assume -task $taskName -bound 1 {_06622_ == 0 }
assume -task $taskName -bound 1 {alu_out_q_t0 == 0 }
assume -task $taskName -bound 1 {cached_insn_opcode_t0 == 0 }
assume -task $taskName -bound 1 {cached_insn_rs1_t0 == 0 }
assume -task $taskName -bound 1 {cached_insn_rs2_t0 == 0 }
assume -task $taskName -bound 1 {count_cycle_t0 == 0 }
assume -task $taskName -bound 1 {count_instr_t0 == 0 }
assume -task $taskName -bound 1 {cpu_state_t0 == 0 }
assume -task $taskName -bound 1 {dbg_next_t0 == 0 }
assume -task $taskName -bound 1 {dbg_rs1val_t0 == 0 }
assume -task $taskName -bound 1 {dbg_rs2val_t0 == 0 }
assume -task $taskName -bound 1 {dbg_valid_insn_t0 == 0 }
assume -task $taskName -bound 1 {decoded_imm_t0 == 0 }
assume -task $taskName -bound 1 {decoded_rd_t0 == 0 }
assume -task $taskName -bound 1 {decoded_rs1_t0 == 0 }
assume -task $taskName -bound 1 {decoded_rs2_t0 == 0 }
assume -task $taskName -bound 1 {decoder_pseudo_trigger_q_t0 == 0 }
assume -task $taskName -bound 1 {decoder_pseudo_trigger_t0 == 0 }
assume -task $taskName -bound 1 {decoder_trigger_q_t0 == 0 }
assume -task $taskName -bound 1 {decoder_trigger_t0 == 0 }
assume -task $taskName -bound 1 {instr_add_t0 == 0 }
assume -task $taskName -bound 1 {instr_addi_t0 == 0 }
assume -task $taskName -bound 1 {instr_and_t0 == 0 }
assume -task $taskName -bound 1 {instr_andi_t0 == 0 }
assume -task $taskName -bound 1 {instr_auipc_t0 == 0 }
assume -task $taskName -bound 1 {instr_beq_t0 == 0 }
assume -task $taskName -bound 1 {instr_bge_t0 == 0 }
assume -task $taskName -bound 1 {instr_bgeu_t0 == 0 }
assume -task $taskName -bound 1 {instr_blt_t0 == 0 }
assume -task $taskName -bound 1 {instr_bltu_t0 == 0 }
assume -task $taskName -bound 1 {instr_bne_t0 == 0 }
assume -task $taskName -bound 1 {instr_ecall_ebreak_t0 == 0 }
assume -task $taskName -bound 1 {instr_fence_t0 == 0 }
assume -task $taskName -bound 1 {instr_jal_t0 == 0 }
assume -task $taskName -bound 1 {instr_jalr_t0 == 0 }
assume -task $taskName -bound 1 {instr_lb_t0 == 0 }
assume -task $taskName -bound 1 {instr_lbu_t0 == 0 }
assume -task $taskName -bound 1 {instr_lh_t0 == 0 }
assume -task $taskName -bound 1 {instr_lhu_t0 == 0 }
assume -task $taskName -bound 1 {instr_lui_t0 == 0 }
assume -task $taskName -bound 1 {instr_lw_t0 == 0 }
assume -task $taskName -bound 1 {instr_or_t0 == 0 }
assume -task $taskName -bound 1 {instr_ori_t0 == 0 }
assume -task $taskName -bound 1 {instr_rdcycle_t0 == 0 }
assume -task $taskName -bound 1 {instr_rdcycleh_t0 == 0 }
assume -task $taskName -bound 1 {instr_rdinstr_t0 == 0 }
assume -task $taskName -bound 1 {instr_rdinstrh_t0 == 0 }
assume -task $taskName -bound 1 {instr_sb_t0 == 0 }
assume -task $taskName -bound 1 {instr_sh_t0 == 0 }
assume -task $taskName -bound 1 {instr_sll_t0 == 0 }
assume -task $taskName -bound 1 {instr_slli_t0 == 0 }
assume -task $taskName -bound 1 {instr_slt_t0 == 0 }
assume -task $taskName -bound 1 {instr_slti_t0 == 0 }
assume -task $taskName -bound 1 {instr_sltiu_t0 == 0 }
assume -task $taskName -bound 1 {instr_sltu_t0 == 0 }
assume -task $taskName -bound 1 {instr_sra_t0 == 0 }
assume -task $taskName -bound 1 {instr_srai_t0 == 0 }
assume -task $taskName -bound 1 {instr_srl_t0 == 0 }
assume -task $taskName -bound 1 {instr_srli_t0 == 0 }
assume -task $taskName -bound 1 {instr_sub_t0 == 0 }
assume -task $taskName -bound 1 {instr_sw_t0 == 0 }
assume -task $taskName -bound 1 {instr_xor_t0 == 0 }
assume -task $taskName -bound 1 {instr_xori_t0 == 0 }
assume -task $taskName -bound 1 {is_alu_reg_imm_t0 == 0 }
assume -task $taskName -bound 1 {is_alu_reg_reg_t0 == 0 }
assume -task $taskName -bound 1 {is_beq_bne_blt_bge_bltu_bgeu_t0 == 0 }
assume -task $taskName -bound 1 {is_compare_t0 == 0 }
assume -task $taskName -bound 1 {is_jalr_addi_slti_sltiu_xori_ori_andi_t0 == 0 }
assume -task $taskName -bound 1 {is_lb_lh_lw_lbu_lhu_t0 == 0 }
assume -task $taskName -bound 1 {is_lui_auipc_jal_t0 == 0 }
assume -task $taskName -bound 1 {is_sb_sh_sw_t0 == 0 }
assume -task $taskName -bound 1 {is_sll_srl_sra_t0 == 0 }
assume -task $taskName -bound 1 {is_slli_srli_srai_t0 == 0 }
assume -task $taskName -bound 1 {is_slti_blt_slt_t0 == 0 }
assume -task $taskName -bound 1 {is_sltiu_bltu_sltu_t0 == 0 }
assume -task $taskName -bound 1 {latched_branch_t0 == 0 }
assume -task $taskName -bound 1 {latched_is_lb_t0 == 0 }
assume -task $taskName -bound 1 {latched_is_lh_t0 == 0 }
assume -task $taskName -bound 1 {latched_rd_t0 == 0 }
assume -task $taskName -bound 1 {latched_stalu_t0 == 0 }
assume -task $taskName -bound 1 {latched_store_t0 == 0 }
assume -task $taskName -bound 1 {mem_addr_t0 == 0 }
assume -task $taskName -bound 1 {mem_do_prefetch_t0 == 0 }
assume -task $taskName -bound 1 {mem_do_rdata_t0 == 0 }
assume -task $taskName -bound 1 {mem_do_rinst_t0 == 0 }
assume -task $taskName -bound 1 {mem_do_wdata_t0 == 0 }
assume -task $taskName -bound 1 {mem_instr_t0 == 0 }
assume -task $taskName -bound 1 {mem_rdata_q_t0 == 0 }
assume -task $taskName -bound 1 {mem_state_t0 == 0 }
assume -task $taskName -bound 1 {mem_valid_t0 == 0 }
assume -task $taskName -bound 1 {mem_wdata_t0 == 0 }
assume -task $taskName -bound 1 {mem_wordsize_t0 == 0 }
assume -task $taskName -bound 1 {mem_wstrb_t0 == 0 }
assume -task $taskName -bound 1 {next_insn_opcode_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_insn_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_rs1_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_rs2_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_timeout_counter_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_timeout_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_valid_t0 == 0 }
assume -task $taskName -bound 1 {q_insn_rs1_t0 == 0 }
assume -task $taskName -bound 1 {q_insn_rs2_t0 == 0 }
assume -task $taskName -bound 1 {reg_next_pc_t0 == 0 }
assume -task $taskName -bound 1 {reg_out_t0 == 0 }
assume -task $taskName -bound 1 {reg_pc_t0 == 0 }
assume -task $taskName -bound 1 {reg_sh_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_halt_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_rmask_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_wdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_wmask_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_order_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_pc_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_pc_wdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rd_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rd_wdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs1_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs1_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs2_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs2_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_valid_t0 == 0 }
assume -task $taskName -bound 1 {trap_t0 == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul ._1029_} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .instr_mul_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .instr_mulh_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .instr_mulhsu_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .instr_mulhu_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .mul_counter_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .mul_finish_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .mul_waiting_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .pcpi_rd_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .pcpi_ready_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .pcpi_wait_q_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .pcpi_wait_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .rd_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .rs1_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .rs2_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .dividend_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .divisor_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .instr_div_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .instr_divu_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .instr_rem_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .instr_remu_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .outsign_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .pcpi_rd_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .pcpi_ready_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .pcpi_wait_q_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .pcpi_wait_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .quotient_msk_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .quotient_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .running_t0} == 0 }
}