# Generated by /data/kceesay/workspace/cellift-formal/py_scripts/fpv_core_setup/taint_states.py
proc no_taint_in_symb_init {taskName} {

assume -task $taskName -bound 1 {_2568_ == 0 }
assume -task $taskName -bound 1 {_2828_ == 0 }
assume -task $taskName -bound 1 {_2830_ == 0 }
assume -task $taskName -bound 1 {_2831_ == 0 }
assume -task $taskName -bound 1 {_2834_ == 0 }
assume -task $taskName -bound 1 {_2846_ == 0 }
assume -task $taskName -bound 1 {alu_out_q_t0 == 0 }
assume -task $taskName -bound 1 {cached_insn_opcode_t0 == 0 }
assume -task $taskName -bound 1 {cached_insn_rs1_t0 == 0 }
assume -task $taskName -bound 1 {cached_insn_rs2_t0 == 0 }
assume -task $taskName -bound 1 {count_cycle_t0 == 0 }
assume -task $taskName -bound 1 {count_instr_t0 == 0 }
assume -task $taskName -bound 1 {dbg_rs1val_t0 == 0 }
assume -task $taskName -bound 1 {dbg_rs2val_t0 == 0 }
assume -task $taskName -bound 1 {decoded_imm_t0 == 0 }
assume -task $taskName -bound 1 {decoded_rd_t0 == 0 }
assume -task $taskName -bound 1 {decoded_rs1_t0 == 0 }
assume -task $taskName -bound 1 {decoded_rs2_t0 == 0 }
assume -task $taskName -bound 1 {latched_rd_t0 == 0 }
assume -task $taskName -bound 1 {mem_16bit_buffer_t0 == 0 }
assume -task $taskName -bound 1 {mem_addr_t0 == 0 }
assume -task $taskName -bound 1 {mem_instr_t0 == 0 }
assume -task $taskName -bound 1 {mem_rdata_q_t0 == 0 }
assume -task $taskName -bound 1 {mem_valid_t0 == 0 }
assume -task $taskName -bound 1 {mem_wdata_t0 == 0 }
assume -task $taskName -bound 1 {mem_wstrb_t0 == 0 }
assume -task $taskName -bound 1 {next_insn_opcode_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_insn_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_rs1_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_rs2_t0 == 0 }
assume -task $taskName -bound 1 {pcpi_valid_t0 == 0 }
assume -task $taskName -bound 1 {q_insn_rs1_t0 == 0 }
assume -task $taskName -bound 1 {q_insn_rs2_t0 == 0 }
assume -task $taskName -bound 1 {reg_next_pc_t0 == 0 }
assume -task $taskName -bound 1 {reg_out_t0 == 0 }
assume -task $taskName -bound 1 {reg_pc_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_rmask_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_wdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_mem_wmask_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_order_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_pc_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_pc_wdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rd_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rd_wdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs1_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs1_rdata_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs2_addr_t0 == 0 }
assume -task $taskName -bound 1 {rvfi_rs2_rdata_t0 == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul ._820_} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .pcpi_rd_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .rd_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk1.genblk1.pcpi_mul .rs2_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .dividend_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .divisor_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .pcpi_rd_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .quotient_msk_t0} == 0 }
assume -task $taskName -bound 1 {{\genblk2.pcpi_div .quotient_t0} == 0 }
}