// Generated by gen_checker_inst.py
bit taint_stop_cond_SHA512SIG1L_op1;
assign taint_stop_cond_SHA512SIG1L_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SIG1L_op2;
assign taint_stop_cond_SHA512SIG1L_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_AES32DSI_op1;
assign taint_stop_cond_AES32DSI_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES32DSI_op2;
assign taint_stop_cond_AES32DSI_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SM4ED_op1;
assign taint_stop_cond_SM4ED_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SM4ED_op2;
assign taint_stop_cond_SM4ED_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA512SUM1_op1;
assign taint_stop_cond_SHA512SUM1_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES32ESI_op1;
assign taint_stop_cond_AES32ESI_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES32ESI_op2;
assign taint_stop_cond_AES32ESI_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA512SUM1R_op1;
assign taint_stop_cond_SHA512SUM1R_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SUM1R_op2;
assign taint_stop_cond_SHA512SUM1R_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA512SIG0L_op1;
assign taint_stop_cond_SHA512SIG0L_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SIG0L_op2;
assign taint_stop_cond_SHA512SIG0L_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SM3P1_op1;
assign taint_stop_cond_SM3P1_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SM3P0_op1;
assign taint_stop_cond_SM3P0_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64ES_op1;
assign taint_stop_cond_AES64ES_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64ES_op2;
assign taint_stop_cond_AES64ES_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA256SIG1_op1;
assign taint_stop_cond_SHA256SIG1_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64IM_op1;
assign taint_stop_cond_AES64IM_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SUM0R_op1;
assign taint_stop_cond_SHA512SUM0R_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SUM0R_op2;
assign taint_stop_cond_SHA512SUM0R_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_AES32DSMI_op1;
assign taint_stop_cond_AES32DSMI_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES32DSMI_op2;
assign taint_stop_cond_AES32DSMI_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA512SUM0_op1;
assign taint_stop_cond_SHA512SUM0_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SIG0_op1;
assign taint_stop_cond_SHA512SIG0_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64ESM_op1;
assign taint_stop_cond_AES64ESM_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64ESM_op2;
assign taint_stop_cond_AES64ESM_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_AES64KS1I_op1;
assign taint_stop_cond_AES64KS1I_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64KS2_op1;
assign taint_stop_cond_AES64KS2_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64KS2_op2;
assign taint_stop_cond_AES64KS2_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA256SIG0_op1;
assign taint_stop_cond_SHA256SIG0_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64DSM_op1;
assign taint_stop_cond_AES64DSM_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64DSM_op2;
assign taint_stop_cond_AES64DSM_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_AES64DS_op1;
assign taint_stop_cond_AES64DS_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES64DS_op2;
assign taint_stop_cond_AES64DS_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA512SIG0H_op1;
assign taint_stop_cond_SHA512SIG0H_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SIG0H_op2;
assign taint_stop_cond_SHA512SIG0H_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA256SUM0_op1;
assign taint_stop_cond_SHA256SUM0_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SIG1H_op1;
assign taint_stop_cond_SHA512SIG1H_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SHA512SIG1H_op2;
assign taint_stop_cond_SHA512SIG1H_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA512SIG1_op1;
assign taint_stop_cond_SHA512SIG1_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SM4KS_op1;
assign taint_stop_cond_SM4KS_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_SM4KS_op2;
assign taint_stop_cond_SM4KS_op2 = cpuregs_rs2_stop_cond;

bit taint_stop_cond_SHA256SUM1_op1;
assign taint_stop_cond_SHA256SUM1_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES32ESMI_op1;
assign taint_stop_cond_AES32ESMI_op1 = cpuregs_rs1_stop_cond;

bit taint_stop_cond_AES32ESMI_op2;
assign taint_stop_cond_AES32ESMI_op2 = cpuregs_rs2_stop_cond;

